spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://182.92.219.202:3306/bank2?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 15090667928Hh_
  redis:
    open: false  # 是否开启redis缓存  true开启   false关闭
      database: 0
      host: 182.92.219.202
      port: 6379
      password: 123456   # 密码（默认为空）
      timeout: 6000ms  # 连接超时时长（毫秒）
      jedis:
        pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5       # 连接池中的最小空闲连接
  zipkin:
    base-url: http://182.92.219.202:9411/ #zipkin 的服务端地址
  sleuth:
    sampler:
      rate: 1 # 采集日志比率 如 0.1

eureka:
  instance:
    prefer-ip-address: true #使用IP地址向Eureka Server注册
  client:
    service-url:
      defaultZone: http://182.92.219.202:8761/eureka/
      #defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
    register-with-eureka: true
    fetch-registry: true

ribbon:
  ConnectTimeout: 50000
  ReadTimeout: 10000
  MaxAutoRetries: 0
  OkToRetryOnAllOperations: false
  ServerListRefreshInterval: 2000
  MaxAutoRetriesNextServer: 3

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000