spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.18.202:3306/hanergy_system?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root123
  redis:
    sentinel:
      nodes: 192.168.18.202:26380
      master: master1
    
    
  #redis:
 #  open: false  # 是否开启redis缓存  true开启   false关闭
   # database: 0
  #  host: 192.168.18.202
  #  port: 6379
  #  password:    # 密码（默认为空）
   # timeout: 6000ms  # 连接超时时长（毫秒）
   # jedis:
   #   pool:
   #     max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
   #     max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
    #    max-idle: 10      # 连接池中的最大空闲连接
    #    min-idle: 5       # 连接池中的最小空闲连接

system:
   standard: http://198.168.18.204/standard/api/v1/dicationary/doRefreshRedis?refresh={0}
   checkPassWord: false
